/*
 * This file is generated by jOOQ.
 */
package com.mybank.co.dao.tables;


import com.mybank.co.dao.Keys;
import com.mybank.co.dao.MyBank;
import com.mybank.co.dao.tables.records.UserRecord;

import java.time.LocalDate;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row8;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User extends TableImpl<UserRecord> {

    private static final long serialVersionUID = 1796347778;

    /**
     * The reference instance of <code>MY_BANK.USER</code>
     */
    public static final User USER = new User();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserRecord> getRecordType() {
        return UserRecord.class;
    }

    /**
     * The column <code>MY_BANK.USER.ID</code>.
     */
    public final TableField<UserRecord, UUID> ID = createField(DSL.name("ID"), org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>MY_BANK.USER.NAME</code>.
     */
    public final TableField<UserRecord, String> NAME = createField(DSL.name("NAME"), org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>MY_BANK.USER.LAST_NAME</code>.
     */
    public final TableField<UserRecord, String> LAST_NAME = createField(DSL.name("LAST_NAME"), org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>MY_BANK.USER.DOCUMENT_TYPE</code>.
     */
    public final TableField<UserRecord, String> DOCUMENT_TYPE = createField(DSL.name("DOCUMENT_TYPE"), org.jooq.impl.SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>MY_BANK.USER.DOCUMENT_ID</code>.
     */
    public final TableField<UserRecord, String> DOCUMENT_ID = createField(DSL.name("DOCUMENT_ID"), org.jooq.impl.SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>MY_BANK.USER.EMAIL</code>.
     */
    public final TableField<UserRecord, String> EMAIL = createField(DSL.name("EMAIL"), org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>MY_BANK.USER.BIRTH_DAY</code>.
     */
    public final TableField<UserRecord, LocalDate> BIRTH_DAY = createField(DSL.name("BIRTH_DAY"), org.jooq.impl.SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>MY_BANK.USER.GENDER</code>.
     */
    public final TableField<UserRecord, String> GENDER = createField(DSL.name("GENDER"), org.jooq.impl.SQLDataType.CHAR(2147483647), this, "");

    /**
     * Create a <code>MY_BANK.USER</code> table reference
     */
    public User() {
        this(DSL.name("USER"), null);
    }

    /**
     * Create an aliased <code>MY_BANK.USER</code> table reference
     */
    public User(String alias) {
        this(DSL.name(alias), USER);
    }

    /**
     * Create an aliased <code>MY_BANK.USER</code> table reference
     */
    public User(Name alias) {
        this(alias, USER);
    }

    private User(Name alias, Table<UserRecord> aliased) {
        this(alias, aliased, null);
    }

    private User(Name alias, Table<UserRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> User(Table<O> child, ForeignKey<O, UserRecord> key) {
        super(child, key, USER);
    }

    @Override
    public Schema getSchema() {
        return MyBank.MY_BANK;
    }

    @Override
    public UniqueKey<UserRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_2;
    }

    @Override
    public List<UniqueKey<UserRecord>> getKeys() {
        return Arrays.<UniqueKey<UserRecord>>asList(Keys.CONSTRAINT_2);
    }

    @Override
    public User as(String alias) {
        return new User(DSL.name(alias), this);
    }

    @Override
    public User as(Name alias) {
        return new User(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public User rename(String name) {
        return new User(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public User rename(Name name) {
        return new User(name, null);
    }

    // -------------------------------------------------------------------------
    // Row8 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row8<UUID, String, String, String, String, String, LocalDate, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }
}
