/*
 * This file is generated by jOOQ.
 */
package com.mybank.co.dao.jooq;


import com.mybank.co.dao.jooq.tables.Account;
import com.mybank.co.dao.jooq.tables.FlywaySchemaHistory;
import com.mybank.co.dao.jooq.tables.Transfer;
import com.mybank.co.dao.jooq.tables.User;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = -2032300468;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>ACCOUNT</code>.
     */
    public final Account ACCOUNT = Account.ACCOUNT;

    /**
     * The table <code>flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>TRANSFER</code>.
     */
    public final Transfer TRANSFER = Transfer.TRANSFER;

    /**
     * The table <code>USER</code>.
     */
    public final User USER = User.USER;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Account.ACCOUNT,
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            Transfer.TRANSFER,
            User.USER);
    }
}
