/*
 * This file is generated by jOOQ.
 */
package com.mybank.co.dao.jooq;


import com.mybank.co.dao.jooq.tables.Account;
import com.mybank.co.dao.jooq.tables.FlywaySchemaHistory;
import com.mybank.co.dao.jooq.tables.Transfer;
import com.mybank.co.dao.jooq.tables.User;


/**
 * Convenience access to all tables in 
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>ACCOUNT</code>.
     */
    public static final Account ACCOUNT = Account.ACCOUNT;

    /**
     * The table <code>flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>TRANSFER</code>.
     */
    public static final Transfer TRANSFER = Transfer.TRANSFER;

    /**
     * The table <code>USER</code>.
     */
    public static final User USER = User.USER;
}
