/*
 * This file is generated by jOOQ.
 */
package com.mybank.co.dao;


import com.mybank.co.dao.tables.Account;
import com.mybank.co.dao.tables.Transfer;
import com.mybank.co.dao.tables.User;
import com.mybank.co.dao.tables.records.AccountRecord;
import com.mybank.co.dao.tables.records.TransferRecord;
import com.mybank.co.dao.tables.records.UserRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>MY_BANK</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AccountRecord> CONSTRAINT_E = UniqueKeys0.CONSTRAINT_E;
    public static final UniqueKey<TransferRecord> CONSTRAINT_7 = UniqueKeys0.CONSTRAINT_7;
    public static final UniqueKey<UserRecord> CONSTRAINT_2 = UniqueKeys0.CONSTRAINT_2;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<AccountRecord, UserRecord> CONSTRAINT_E4 = ForeignKeys0.CONSTRAINT_E4;
    public static final ForeignKey<TransferRecord, AccountRecord> CONSTRAINT_7A = ForeignKeys0.CONSTRAINT_7A;
    public static final ForeignKey<TransferRecord, AccountRecord> CONSTRAINT_7AF = ForeignKeys0.CONSTRAINT_7AF;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<AccountRecord> CONSTRAINT_E = Internal.createUniqueKey(Account.ACCOUNT, "CONSTRAINT_E", new TableField[] { Account.ACCOUNT.ID }, true);
        public static final UniqueKey<TransferRecord> CONSTRAINT_7 = Internal.createUniqueKey(Transfer.TRANSFER, "CONSTRAINT_7", new TableField[] { Transfer.TRANSFER.ID }, true);
        public static final UniqueKey<UserRecord> CONSTRAINT_2 = Internal.createUniqueKey(User.USER, "CONSTRAINT_2", new TableField[] { User.USER.ID }, true);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<AccountRecord, UserRecord> CONSTRAINT_E4 = Internal.createForeignKey(Keys.CONSTRAINT_2, Account.ACCOUNT, "CONSTRAINT_E4", new TableField[] { Account.ACCOUNT.USER_ID }, true);
        public static final ForeignKey<TransferRecord, AccountRecord> CONSTRAINT_7A = Internal.createForeignKey(Keys.CONSTRAINT_E, Transfer.TRANSFER, "CONSTRAINT_7A", new TableField[] { Transfer.TRANSFER.SOURCE_ACCOUNT_ID }, true);
        public static final ForeignKey<TransferRecord, AccountRecord> CONSTRAINT_7AF = Internal.createForeignKey(Keys.CONSTRAINT_E, Transfer.TRANSFER, "CONSTRAINT_7AF", new TableField[] { Transfer.TRANSFER.TARGET_ACCOUNT_ID }, true);
    }
}
