/*
 * This file is generated by jOOQ.
 */
package com.mybank.co.dao;


import com.mybank.co.dao.tables.Account;
import com.mybank.co.dao.tables.Transfer;
import com.mybank.co.dao.tables.User;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MyBank extends SchemaImpl {

    private static final long serialVersionUID = -590929524;

    /**
     * The reference instance of <code>MY_BANK</code>
     */
    public static final MyBank MY_BANK = new MyBank();

    /**
     * The table <code>MY_BANK.ACCOUNT</code>.
     */
    public final Account ACCOUNT = Account.ACCOUNT;

    /**
     * The table <code>MY_BANK.TRANSFER</code>.
     */
    public final Transfer TRANSFER = Transfer.TRANSFER;

    /**
     * The table <code>MY_BANK.USER</code>.
     */
    public final User USER = User.USER;

    /**
     * No further instances allowed
     */
    private MyBank() {
        super("MY_BANK", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Account.ACCOUNT,
            Transfer.TRANSFER,
            User.USER);
    }
}
