/*
 * This file is generated by jOOQ.
 */
package com.mybank.co.dao;


import com.mybank.co.dao.tables.Account;
import com.mybank.co.dao.tables.Transfer;
import com.mybank.co.dao.tables.User;


/**
 * Convenience access to all tables in MY_BANK
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>MY_BANK.ACCOUNT</code>.
     */
    public static final Account ACCOUNT = Account.ACCOUNT;

    /**
     * The table <code>MY_BANK.TRANSFER</code>.
     */
    public static final Transfer TRANSFER = Transfer.TRANSFER;

    /**
     * The table <code>MY_BANK.USER</code>.
     */
    public static final User USER = User.USER;
}
